package fr.fortytwo.orm.manager;

import fr.fortytwo.orm.annotations.OrmColumn;
import fr.fortytwo.orm.annotations.OrmColumnId;
import fr.fortytwo.orm.annotations.OrmEntity;

import javax.sql.DataSource;
import java.lang.reflect.Field;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.StringJoiner;

public class OrmManager {
    private final DataSource dataSource;

    public OrmManager(DataSource dataSource, String... packageNames) {
        this.dataSource = dataSource;
        initTables();
    }

    private void initTables() {
        // Drop and recreate tables for annotated entities (e.g., User)
        Class<fr.fortytwo.orm.models.User> clazz = fr.fortytwo.orm.models.User.class;
        if (!clazz.isAnnotationPresent(OrmEntity.class)) return;

        String tableName = clazz.getAnnotation(OrmEntity.class).table();
        String dropSql = "DROP TABLE IF EXISTS " + tableName + " CASCADE;";

        StringJoiner columnsSql = new StringJoiner(", ");
        for (Field field : clazz.getDeclaredFields()) {
            if (field.isAnnotationPresent(OrmColumnId.class)) {
                columnsSql.add(field.getName() + " BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
            } else if (field.isAnnotationPresent(OrmColumn.class)) {
                OrmColumn col = field.getAnnotation(OrmColumn.class);
                columnsSql.add(col.name() + " " + getSqlType(field.getType(), col.length()));
            }
        }

        String createSql = "CREATE TABLE " + tableName + " (" + columnsSql + ");";

        executeSql(dropSql);
        executeSql(createSql);
    }

    public void save(Object entity) {
        Class<?> clazz = entity.getClass();
        if (!clazz.isAnnotationPresent(OrmEntity.class)) return;

        String tableName = clazz.getAnnotation(OrmEntity.class).table();
        StringJoiner columns = new StringJoiner(", ");
        StringJoiner values = new StringJoiner(", ");
        Field idField = null;

        for (Field field : clazz.getDeclaredFields()) {
            field.setAccessible(true);
            if (field.isAnnotationPresent(OrmColumnId.class)) {
                idField = field;
            } else if (field.isAnnotationPresent(OrmColumn.class)) {
                OrmColumn col = field.getAnnotation(OrmColumn.class);
                columns.add(col.name());
                try {
                    Object val = field.get(entity);
                    values.add(val == null ? "NULL" : "'" + val + "'");
                } catch (IllegalAccessException e) {
                    e.printStackTrace();
                }
            }
        }

        String sql = "INSERT INTO " + tableName + " (" + columns + ") VALUES (" + values + ");";
        executeSql(sql);

        // Retrieve generated ID (H2/PostgreSQL compliant)
        if (idField != null) {
            String lastIdSql = "SELECT MAX(" + idField.getName() + ") FROM " + tableName + ";";
            try (Connection conn = dataSource.getConnection();
                 Statement stmt = conn.createStatement();
                 ResultSet rs = stmt.executeQuery(lastIdSql)) {
                if (rs.next()) {
                    idField.set(entity, rs.getLong(1));
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    public void update(Object entity) {
        Class<?> clazz = entity.getClass();
        if (!clazz.isAnnotationPresent(OrmEntity.class)) return;

        String tableName = clazz.getAnnotation(OrmEntity.class).table();
        StringJoiner updates = new StringJoiner(", ");
        Object idValue = null;

        for (Field field : clazz.getDeclaredFields()) {
            field.setAccessible(true);
            try {
                if (field.isAnnotationPresent(OrmColumnId.class)) {
                    idValue = field.get(entity);
                } else if (field.isAnnotationPresent(OrmColumn.class)) {
                    OrmColumn col = field.getAnnotation(OrmColumn.class);
                    Object val = field.get(entity);
                    updates.add(col.name() + " = " + (val == null ? "NULL" : "'" + val + "'"));
                }
            } catch (IllegalAccessException e) {
                e.printStackTrace();
            }
        }

        String sql = "UPDATE " + tableName + " SET " + updates + " WHERE id = " + idValue + ";";
        executeSql(sql);
    }

    public <T> T findById(Long id, Class<T> aClass) {
        if (!aClass.isAnnotationPresent(OrmEntity.class)) return null;

        String tableName = aClass.getAnnotation(OrmEntity.class).table();
        String sql = "SELECT * FROM " + tableName + " WHERE id = " + id + ";";
        executeSql(sql);

        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {

            if (rs.next()) {
                T instance = aClass.getDeclaredConstructor().newInstance();
                for (Field field : aClass.getDeclaredFields()) {
                    field.setAccessible(true);
                    if (field.isAnnotationPresent(OrmColumnId.class)) {
                        field.set(instance, rs.getLong("id"));
                    } else if (field.isAnnotationPresent(OrmColumn.class)) {
                        OrmColumn col = field.getAnnotation(OrmColumn.class);
                        Object value = rs.getObject(col.name());
                        field.set(instance, castValue(value, field.getType()));
                    }
                }
                return instance;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

    private void executeSql(String sql) {
        System.out.println(sql); // Required: OrmManager must log generated SQL statements
        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement()) {
            stmt.execute(sql);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private String getSqlType(Class<?> type, int length) {
        if (type.equals(String.class)) return "VARCHAR(" + length + ")";
        if (type.equals(Integer.class) || type.equals(int.class)) return "INT";
        if (type.equals(Long.class) || type.equals(long.class)) return "BIGINT";
        if (type.equals(Double.class) || type.equals(double.class)) return "DOUBLE PRECISION";
        if (type.equals(Boolean.class) || type.equals(boolean.class)) return "BOOLEAN";
        return "VARCHAR(255)";
    }

    private Object castValue(Object value, Class<?> targetType) {
        if (value == null) return null;
        if (targetType.equals(Integer.class) || targetType.equals(int.class)) return ((Number) value).intValue();
        if (targetType.equals(Long.class) || targetType.equals(long.class)) return ((Number) value).longValue();
        if (targetType.equals(Double.class) || targetType.equals(double.class)) return ((Number) value).doubleValue();
        return value;
    }
}